### ISSUE TITLE
Avoid short comparsions

### ISSUE THREAD

**Issue by ostrichby** [VIVern/godel-lab#2]
To avoid typecasting always use comparsions e.g. if (isset($a) === true) instead of if ($a)
P. S. Nice workaround, but might be possible checking if we are running from browser from more reliable source?

https://github.com/VIVern/godel-lab/blob/672ac67a89a767e32e19704713a8c964b2b4d376/index.php#L8

**Comment by VIVern** [comment]
added === true

**Comment by VIVern** [comment]
> P. S. Nice workaround, but might be possible checking if we are running from browser from more reliable source?

now using $_SERVER array if you meant this

**Comment by VIVern** [comment]
done
